### PR TITLE
Add input files for invalid test cases

### LINKED ISSUE #5: Add invalid test cases
Just a few examples of invalid usage

### PR DESCRIPTION
**Pull request by tohanss**
Fix #5

### CODE REVIEW

**Comment by slarse** [comment]
@tohanss Did you close this on accident?

**Comment by tohanss** [comment]
@slarse More like pushed it by accident. Wanted to abide by the concept of "commit often" and on autopilot pushed as well, don't think that was necessary until I finish

**Comment by slarse** [comment]
@tohanss That's fine, just add a "wip" in the PR title to indicate that you're not done yet.

**Comment by slarse** [comment]
Like that

**Pull request merged**
