### PR TITLE
Bugifx for string matching on tracked and untracked

### PR DESCRIPTION
**Pull request by tohanss**

### CODE REVIEW

**Comment by tohanss** [comment]
What is the PR tag for bugfix? is it [bug] or [bugfix] or something else

**Comment by tohanss** [comment]
Closed because the bugfix somehow made it into the other PR despite being on different branches

If you read this: What did i do wrong?

**Comment by slarse** [comment]
@tohanss The tag is `[fix]`. Should probably be documented.

Anyway, there are two things that have gone wrong here.

First, you're reusing a branch that's all ready been merged. That's both confusing, and will often lead to merge conflicts as we use squashing. So, never reuse a merged branch.

Second, you first made these changes for this PR, then you branched out from _this_ branch to the one used in #36 , instead of branching out from a synced master. You should always branch out from master, and make sure that master is up-to-date.

**Comment by slarse** [comment]
Now, let's fix this.

First, sync master. Then, branch out from master and recreate the intended changes from this PR (either by cherry picking, or by just making a new commit since the changes are so few). Then open a new PR.

**Pull request closed without merging**
