### PR TITLE
[feat] Add --ignore-list command

### LINKED ISSUE #79: Add --ignore-list to discover mode
It should be possible to ignore certain files. This list should be on the same form as the old `--file-list` option.

### PR DESCRIPTION
**Pull request by tohanss**
Works as expected during manual testing.

Before merging I want to add so that the terminal reports what files were ignored, for clarity

Fix #79

### CODE REVIEW

**Comment by tohanss** [comment]
I realize that im going to have to change this to use filepaths instead of just file names

**Comment by tohanss** [comment]
Now i just want to change it so the success message doesnt just tell us what files are in the ignore list and instead tells us what files were ignored, and what files were not found

**Comment by tohanss** [comment]
The ignore file-list is now ignored by having a shred marker at the top of the file.

**Comment by slarse** [comment]
@tohanss Could you post some example output? I'm to lazy to actually run it.

**Comment by tohanss** [comment]
It do look a little something like this: 
image

Please note that the file doesnt-exist.txt inside the subdir folder DOES exist

**Pull request closed without merging**
